### ISSUE TITLE
Add libxlsxwriter topic to the project metadata

### ISSUE THREAD

**Issue by jmcnamara** [nobody246/xlsxWriterScm#1]
Hi,

Could you add libxlsxwriter as a "topic" metadata to your project so that users can find wrappers in different languages.

Topic/Metadata are shown at the top of the project: https://github.com/jmcnamara/libxlsxwriter

Other examples: https://github.com/search?q=topic%3Alibxlsxwriter&type=Repositories

Thanks,

John

**Comment by nobody246** [comment]
Hi John,
   Sorry I didn't see your comment sooner but I added in the topics, should be good to go.

Thanks

**Comment by jmcnamara** [comment]
Thanks.
